### ISSUE TITLE
Wrong cmt chars

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#11]
- set for C stm cmt chars: `/**, **/`
- restart
- new file, C, make some stm comment. ok
- open cmt chars dialog, fix cmt chars back: `/*, */`
- same file, C, make some stm cmt: not OK! still cmt with `/** **/`

**Comment by kvichans** [comment]
Зачем-то нужен еще один перевызов Куд

**Comment by kvichans** [comment]
А-а-а. Знаю! Плаг кеширует эти пары.
Поправлю.
