### ISSUE TITLE
Dupl Line cmd

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#13]
Это спорно. Можно выделить dupl line тоже в плагин из cuda_lib
- команда Дубл не относится к cuda_lib
- можно сделать диалог (опц) и cuda_lib не попортится

**Comment by kvichans** [comment]
Да, это верно.
Но сейчас не хватает "общей идеи": _какие_ из функций за пределами ядра _где_ будут размещаться?

**Comment by Alexey-T** [comment]
пока только Dup, Comments. где - группа команд в 1 плаге.
