### ISSUE TITLE
Synw version

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#19]
Сложно ли сделать версию для Син? я бы тоже там выкинул, и к тому же там код для коментов- EControl, что нельзя поддерживать

**Comment by kvichans** [comment]
Сейчас мне сложно переключаться. И давно уже не был в Сине - забыл как там жить.

**Comment by Alexey-T** [comment]
сделал порт методов "для line cmts"- уже работает. Но не могу делать метод strm cmt- там много ed.delete, ed.set_caret, думаю что надо новый метод для син написать. чтобы брал ed.get_text_sel() - добавил к нему /\* */ и ставил блок обратно
Приделаю к син еще lexer_get_comment_stream/ lexer_get_comment_lined чтобы хранились коменты также
