### ISSUE TITLE
Error if called for unknown lexer

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#22]
cmt_sgn     = app.lexer_proc(app.LEXER_GET_PROP,    lex)['c_line']     if lex else ''

Надо проверить рез-т lexer_proc()

**Comment by Alexey-T** [comment]
pair1 = app.lexer_proc(app.LEXER_GET_PROP, lex)['c_str']
           pair2 = app.lexer_proc(app.LEXER_GET_PROP, lex)['c_lined']

и тут.

**Comment by kvichans** [comment]
Ok

**Comment by Alexey-T** [comment]
Не решено
```
        cmt_sgn     = app.lexer_proc(app.LEXER_GET_PROP,    lex)['c_line']     if lex else ''
#       cmt_sgn     = app.lexer_proc(app.LEXER_GET_COMMENT, lex)
```
вот так у вас.

**Comment by Alexey-T** [comment]
В репо Куд это решено. плис, возьмите мои правки

**Comment by kvichans** [comment]
ок
