### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by igorog** [kvichans/cuda_comments#29]
`Operating System: Arch Linux
Kernel Version: 5.10.8-arch1-1
OS Type: 64-bit
Processors: 4 × Intel® Core™ i7-3537U CPU @ 2.00GHz
Memory: 7.7 ГиБ of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4000

"pylib__linux" : "/usr/lib/libpython3.9.so.1.0"`
```
ttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/ussr/.config/cudatext/py/cuda_comments/cd_comments.py", line 71, in cmt_toggle_line_1st
    return self._cmt_toggle_line('bgn', '1st')
  File "/home/ussr/.config/cudatext/py/cuda_comments/cd_comments.py", line 130, in _cmt_toggle_line
    save_bd_col = apx.get_opt('comment_save_column' , False)
  File "/home/ussr/.config/cudatext/py/cudax_lib.py", line 240, in get_opt
    ,usr_opts.get(path
AttributeError: 'NoneType' object has no attribute 'get'`
```

**Comment by Alexey-T** [comment]
@igorog  What steps did you do to see this error?

**Comment by igorog** [comment]
> What steps did you do to see this error?

I just click any item in the comments menu
![screensh](https://user-images.githubusercontent.com/38178476/105148275-c7983480-5b34-11eb-95d0-3c2283a0146a.png)

**Comment by Alexey-T** [comment]
You have wrong user.json: too many `{ }`. See about JSON format in the web?

**Comment by igorog** [comment]
> You can wrong user.json: too many `{ }`

Oops, I'm sorry. (( I fixed it and Plugin "Comments" worked (issue сan be closed), but Plugin "Find in Files" did not work anyway

**Comment by Alexey-T** [comment]
closing this issue.
