### ISSUE TITLE
Remove/Add line comment

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_comments#3]
- add line cmt at line start
- add line cmt at non-space char
- remove line cmt

они иногда нужны, потому что кусок может быть коменчен не весь, часть строк коменчена, часть нет, потом снова часть коменчена

пример

```
  code
  //code
  //code
  some text
  some
  //cmt
  //cmt
```

Тут надо везде добавить //

**Comment by kvichans** [comment]
Может быть когда-нибудь это добавлю.
Текущие `Toggle*` уже позволяют это делать. Только нужно выделять строки аккуратно:
- если первая выделенная строка была с комментарием, то все станут без,
- если первая была без, то все станут с комментарием.

**Comment by Alexey-T** [comment]
Без кмд юзеры будут недов.--часть команд пропала!

**Comment by Alexey-T** [comment]
`do_uncmt    = ed_.get_text_line(rWrks[0]).lstrip().startswith(cmt_sgn)`
тут рефакторить можно. чтобы было add-remov-toggle.

**Comment by kvichans** [comment]
Да, хорошая идея. Сейчас сделаю

**Comment by Alexey-T** [comment]
PullReq
